# Project Name
TARGET = i2c_test

# Sources
CPP_SOURCES = i2c_test.cpp

# Library Locations
LIBDAISY_DIR = $(HOME)/lib/Daisy/libDaisy
DAISYSP_DIR = $(HOME)/lib/Daisy/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
